### ISSUE TITLE
Negate whenOSX

### ISSUE THREAD

**Issue by nojaf** [slaveOftime/Fun.Build#10]
Hello,

I would like to skip running a stage when the OS is `OSX`.
Can I currently do this?

**Comment by MangelMaxime** [comment]
There seems to exist `whenLinux`, `whenWindows`, `whenOSX`

https://github.com/slaveOftime/Fun.Build/blob/bce93c4a26490428514bb6ac2b03598a7868090b/Fun.Build/ConditionsBuilder.fs#L117-L143

But, they doesn't seems to be available inside of the `whenAny` builder.

**Comment by albertwoo** [comment]
@MangelMaxime  @nojaf  whenLinux and whenWindows is just a top level helper for stage context.
Under whenAny or whenAll, you can use platformOSX.

**Comment by nojaf** [comment]
Yes, all these things exist, but the lack of a clear answer indicates that you currently cannot do any of this at the stage level. There is no way to pass in a `WhenAnyBuilder` at the stage level.

It is also not clear to be if `whenLinux` and `whenWindows` can be used together or if the last one will take precedence.

Could we add something at the stage level, please?

**Comment by albertwoo** [comment]
@nojaf Can you share a demo code for what you want to achieve? I did not get the point. Also you say "There is no way to pass in a WhenAnyBuilder at the stage level." Actually it does:
```fsharp
stage "Demo2" {
        // whenAny, whenNot, whenAll. They can also be composed.
        whenAny {
            platformOSX
            platformLinux
        }
        run "dotnet --version""
}
```

For "It is also not clear to be if whenLinux and whenWindows can be used together or if the last one will take precedence", we may need to update the function comments to indicate that the last one will take effect.

**Comment by nojaf** [comment]
I was trying something like:

```fsharp
    stage "Docs" {
        when'(whenNot { platformOSX })
        run "dotnet fsi ./docs/.style/style.fsx"
    }
```

the confusing part is that there is no `[<CustomOperation("when'")>]` on the `StageBuilder`.
This led me to believe that you can't put conditions on stages.

Given your example, I've settled upon:

```fsharp
stage "Docs" {
        whenNot { platformOSX }
        run "dotnet fsi ./docs/.style/style.fsx"
}
```

Thanks for elaborating.
