### ISSUE TITLE
Possibility to lower FSharp.Core requirements?

### ISSUE THREAD

**Issue by MangelMaxime** [slaveOftime/Fun.Build#11]
Current version of Fun.Build has been published with the requirements `FSharp.Core >= 6.0.6`

Would it be possible to lower the requirement to something like `4.7.2` or `5.0.2` if you are using v5 features?

This would avoid warnings like:

```
C:\Users\mange\AppData\Local\Temp\94892--e27d2af4-b61e-4083-b280-0ec53ae62158\Project.fsproj : warning NU1605: Detected package downgrade: FSharp.Core from 6.0.6 to 6.0.5. Reference the package directly from the project to select a different version.
C:\Users\mange\AppData\Local\Temp\94892--e27d2af4-b61e-4083-b280-0ec53ae62158\Project.fsproj : warning NU1605:  Project -> Fun.Build 0.1.6 -> FSharp.Core (>= 6.0.6)
C:\Users\mange\AppData\Local\Temp\94892--e27d2af4-b61e-4083-b280-0ec53ae62158\Project.fsproj : warning NU1605:  Project -> FSharp.Core (>= 6.0.5)
C:\Users\mange\AppData\Local\Temp\94892--e27d2af4-b61e-4083-b280-0ec53ae62158\Project.fsproj : warning NU1605: Detected package downgrade: FSharp.Core from 6.0.6 to 6.0.5. Reference the package directly from the project to select a different version.
C:\Users\mange\AppData\Local\Temp\94892--e27d2af4-b61e-4083-b280-0ec53ae62158\Project.fsproj : warning NU1605:  Project -> Fun.Build 0.1.6 -> FSharp.Core (>= 6.0.6)
C:\Users\mange\AppData\Local\Temp\94892--e27d2af4-b61e-4083-b280-0ec53ae62158\Project.fsproj : warning NU1605:  Project -> FSharp.Core (>= 6.0.5)
```

Lowering the requirement consist in adding a line like `<PackageReference Update="FSharp.Core" Version="4.7.*" />`  to the fsproj.

**Comment by albertwoo** [comment]
@MangelMaxime Sorry I have to close this. Some features like InlineIfLambda and CustomOperation is only available after F# 6.

**Comment by MangelMaxime** [comment]
Would a lower version of FSharp.Core 6 works?

On my computer I am using SDK 6.0.302, which is not that old it has been published the July 12, 2022.

And no problem if you can't as you are using feature specific to F# 6 :)

**Comment by albertwoo** [comment]
That will be fine. I will update that.

**Comment by albertwoo** [comment]
Set to 6.0.0 now.

**Comment by MangelMaxime** [comment]
Awesome thank you not having the warning at the top make a huge difference in term of feeling :)
