### ISSUE TITLE
Make console output a bit lighter?

### ISSUE THREAD

**Issue by MangelMaxime** [slaveOftime/Fun.Build#13]
I find that seeing lines with a lot of "---" makes the output difficult to read or make me feel like something went wrong.

![image](https://user-images.githubusercontent.com/4760796/192624554-8b8d2a4d-1843-4107-aa16-f3c0d1bc6e71.png)

What do you think of using empty lines instead to separates the stages?

**Comment by albertwoo** [comment]
@MangelMaxime sure we can, before I use gray is because I thought that meta information is not important and do not want to distract users focus.
Do you have any preferred color?

**Comment by MangelMaxime** [comment]
What I am speaking about is the `----------` lines. 

Not sure, what you want to apply the grey to?

My proposition is to change the out put to something like that:

```
── STAGE #1 Restore tools and dependencies started. Stage timeout: -1ms. Step timeout: ─────────

Clean/step-0> started:
Clean/step-0> finished. 9ms.

── STAGE #1 Restore tools and dependencies finished. 2329ms. ─────────────────────────


── STAGE #3 Publish started. Stage timeout: -1ms. Step timeout: -1ms. ────────────────────
```

See how there are no double `-------` lines anymore between the stage but just new lines.

**Comment by albertwoo** [comment]
Oh, I thought lighter is for brighter 😅.
Replace with new lines is ok for me. I will change that.

**Comment by albertwoo** [comment]
Will close this, the changes should be in 0.1.7.
