### ISSUE TITLE
Auto generate help message?

### ISSUE THREAD

**Issue by MangelMaxime** [slaveOftime/Fun.Build#16]
Do you think it would be possible for `Fun.Build` to generate the help message?

In Fable.Packages build script I work around this limitation by doing, checking the `args` manually.

```fs
#r "nuget: Fun.Build, 0.1.8"

open Fun.Build
open System
open System.IO

let args = Environment.GetCommandLineArgs()

let isHelp = Seq.contains "--help" args || Seq.contains "help" args

if isHelp then
    printfn
        """
Usage: dotnet fsi build.fsx [options]

Options:
    --watch         Start a local web server and watch for changes
    --publish       Build a production version of the site and publish it on GitHub Pages
    --help, help    Show this help
    """

    exit 0

module Directory =

    let deleteIfExists path =
        if Directory.Exists path then
            Directory.Delete(path, true)

module Path =

    let src = Path.Combine(__SOURCE_DIRECTORY__, "src")

pipeline "Fable.Packages" {
    workingDir __SOURCE_DIRECTORY__

    stage "Clean" {
        run (fun ctx ->
            Directory.deleteIfExists "src/bin"
            Directory.deleteIfExists "src/obj"
        )
    }

    stage "Restore tools and dependencies" {
        run "npm install"
        run "dotnet tool restore"
    }

    stage "Watch" {
        whenCmdArg "--watch"
        workingDir Path.src
        paralle
        stage "Vite" { run "npx vite dev" }
        stage "Fable" { run "dotnet fable --watch" }
    }

    stage "Publish" {
        whenCmdArg "--publish"
        workingDir Path.src
        run "dotnet fable"
        run "npx vite build"
        run "npx gh-pages -d dist"
    }

    runIfOnlySpecified false
}
```

In theory, Fun.Build as a lot of information about the different stage and could add a `description` keyword for the user to supply it.

**Comment by albertwoo** [comment]
@MangelMaxime Yes, I was thinking about that before too. Will try to find time to implement that.

**Comment by albertwoo** [comment]
@MangelMaxime with version 0.2.1, you can do this:

To add description to your command you can do like below:
```fsharp
stage "Watch" {
    whenCmdArg "--watch" "" "watch vite and fable tool"
}
```

Also call **tryPrintPipelineCommandHelp ()** at the end of your script file.

```bash
dotnet fsi .\demo.fsx -- -h
```
![image](https://user-images.githubusercontent.com/8017681/198180303-1b123668-a389-4e2f-8c96-37d5e81ea449.png)

You can also check verbose help information:
```bash
dotnet fsi .\demo.fsx -- -h --verbose
```
![image](https://user-images.githubusercontent.com/8017681/198180209-44f82a5c-0fed-4f58-bf69-8acd29a09a2f.png)

**Comment by MangelMaxime** [comment]
What is the empty string in the middle of `whenCmdArg "--watch" "" "watch vite and fable tool"`

Does that mean that if I have 2 cmd, I need to duplicate the message?

```fs
    stage "Watch" {
        whenAny {
            cmdArg "watch" "" "Start a local web server and watch for changes"
            cmdArg "--watch" "" "Start a local web server and watch for changes"
        }
```

---------

It would be better if the `your_script.fsx` was actually using the name of the script. This is because, if I am a user and see a help message, I expect that if I copy/paste it it should work.

Here, I suppose it will not work unless the script is actually named: `your_script.fsx`

---------

Sorry to say it after the implementation, but I had something else in mind.

I had more something like a standard CLI help in mind.

Kind of like how `dotnet` works for example.

You have different level of information depending on where you are in the "tree":

- `dotnet --help`: Give the general help message for all the command supported
- `dotnet add --help`: Give the help message for that specific command

So for Fun.Build, it would be something like:

1. Give general help message on the available pipelines
2. Give help message for the specified pipeline

It would also, be able to improve the help message based on the context:
- Are there only one pipeline?
- Is the pipeline flagged with `runIfOnlySpecified false`?
- Are there some `cmd` conditions?
- Are there some `env` conditions?

Below I am trying to illustrate what I mean:

## Only one pipeline with `runIfOnlySpecified true`, with some stages controlled via `cmd`

```fs
pipeline "Documentation" {
    workingDir __SOURCE_DIRECTORY__
	description "This pipeline is used when working on the documentation"

    stage "Clean" {
        run (fun _ ->
            Directory.deleteIfExists "./_site"
            Directory.deleteIfExists "./_11ty/_js/"
        )
    }

    stage "Watch" {
		description "Start a local web server and watch for changes"
        whenAny {
            cmdArg "watch"
            cmdArg "--watch"
        }

	runIfOnlySpecified true // I make it explicit for the explanations
}
```

Help generated:

*Note: `build.fsx` is the real name of the script, not something generic because the help message would not be that useful otherwise*

Because there is only one `pipeline`, running only if specified the script is usable only if the user run `dotnet fsi build.fsx -p Site`

```
Usage: dotnet fsi build.fsx -p Site [options]

	This pipeline is used when working on the documentation

Options:
	--watch, watch 		"Start a local web server and watch for changes"
	--help, help			Show the help message
```

## Only one pipeline with `runIfOnlySpecified false`, with some stages controlled via `cmd`


```fs
pipeline "Documentation" {
    workingDir __SOURCE_DIRECTORY__
	description "This pipeline is used when working on the documentation"

    stage "Clean" {
        run (fun _ ->
            Directory.deleteIfExists "./_site"
            Directory.deleteIfExists "./_11ty/_js/"
        )
    }

    stage "Watch" {
		description "Start a local web server and watch for changes"
        whenAny {
            cmdArg "watch"
            cmdArg "--watch"
        }

	runIfOnlySpecified false // I make it explicit for the explanations
}
```

Help generated:

User doesn't need to specify the pipeline, so `[-p Site]` is optional.

```
Usage: dotnet fsi build.fsx [-p Site] [options]

	This pipeline is used when working on the documentation

Options:
	--watch, watch 		"Start a local web server and watch for changes"
	--help, help			Show the help message
```

## Several pipelines with `runIfOnlySpecified true`

```fs
pipeline "Documentation" {
    workingDir __SOURCE_DIRECTORY__
	description "Work on the documentation"

    stage "Clean" {
        run (fun _ ->
            Directory.deleteIfExists "./_site"
            Directory.deleteIfExists "./_11ty/_js/"
        )
    }

    stage "Watch" {
		description "Start a local web server and watch for changes"
        whenAny {
            cmdArg "watch"
            cmdArg "--watch"
        }

	runIfOnlySpecified true // I make it explicit for the explanations
}

pipeline "Packages" {
    workingDir __SOURCE_DIRECTORY__
	description "Publish the packages to NuGet"

    stage "Clean" {
        run (fun _ ->
            Directory.deleteIfExists "./_site"
            Directory.deleteIfExists "./_11ty/_js/"
        )
    }

	stage "Test" {
		description "Check that the test are passing"
		run "dotnet tests"
		// ...
	}

    stage "Publish" {
		description "Publish packages to NuGet"
		// ...
	}

	runIfOnlySpecified true // I make it explicit for the explanations
}
```

Help generated:

```
Usage: dotnet fsi build.fsx [command-options] [-p <pipeline>]

	This pipeline is used when working on the documentation

pipeline:
	Documentation		Work on the documentation
	Packages				Publish the packages to NuGet

command-options:
	--help, help			Show the help message
```

And then if the user run `dotnet fsi build.fsx -p Packages --help`

He sees:

```
Usage: dotnet fsi build.fsx -p Documentation [options]

	This pipeline is used when working on the documentation

options:
	--watch, watch		Start a local web server and watch for changes
	--help, help			Show the help message
```

**Comment by albertwoo** [comment]
@MangelMaxime the whitespace is for the related value, sometimes I may write **--cmdArg cmdValue**. So I can try to match cmdValue.

```fsharp
whenCmdArg "--cmdArg" "cmdValue"
```
More docs is needed 😂.

The description should be very easy to add. All other suggestions looks good too. You are also welcomed to make a PR for that.

**Comment by MangelMaxime** [comment]
> @MangelMaxime the whitespace is for the related value, sometimes I may write **--cmdArg cmdValue**. So I can try to match cmdValue.
> 
> ```fsharp
> whenCmdArg "--cmdArg" "cmdValue"
> ```

Ah yes, I forget about that :)

Good to hear, you are open to it. When I have the time I will git it a try :)

**Comment by albertwoo** [comment]
@MangelMaxime I release 0.2.4, added description and improved the format. But may still need some polish.

**Comment by MangelMaxime** [comment]
@albertwoo I am still to explore all the cases covered by the new help format.

But it seems really cool 😍

**Comment by albertwoo** [comment]
Will close this, because in recent releases, it is improved a lot.
