### ISSUE TITLE
Questions: Pipeline vs Stages?

### ISSUE THREAD

**Issue by MangelMaxime** [slaveOftime/Fun.Build#17]
*Sorry for the bad title of the issue, I didn't know how to name it...*

I am not really sure what the pipeline are for.

In my use case, I have the following workflow that I want to happen:

- Clean -> Tests
- Clean -> Tests -> Release

My first idea, was to use a single `pipeline`with conditional stages but it seems to add too much ceremony.

```fs
pipeline "Thoth.Json.Net" {
    description "Adapt test files to Thoth.Json.Net and normalize line endings"
    workingDir __SOURCE_DIRECTORY__

    stage "Clean" {
        run (fun _ ->
            !! "src/**/bin"
            ++ "src/**/obj"
            ++ "tests/**/bin"
            ++ "tests/**/obj"
            ++ "temp/"
            |> Shell.cleanDirs
        )
    }

    stage "Test" {
        whenAny {
            cmdArg "test" "" "Run the tests"
            cmdArg "release" "" "Release a new version to Nuget" // See here, I need to have the `release` cmd to have it run when releasing a new version
        }

        run "dotnet tests"
    }

    stage "Release" {
        whenCmdArg "release" "" "Release a new version to Nuget"
        
        // Do something
    }

    runIfOnlySpecified false
}
```

Should I use several pipeline in that case? Can stages be re-used?

**Comment by MangelMaxime** [comment]
I tried to create the stage in a separate `module` to be able to re-use them, but something seems to be missing in the CE implementation for that scenario to be supported.

```fs
pipeline "Test" {
    description "Adapt test files to Thoth.Json.Net and normalize line endings"
    workingDir __SOURCE_DIRECTORY__

    Stages.clean
    Stages.adaptTest
    Stages.test

}

pipeline "Release" {
    description "Release a new version on NuGet"

    Stages.clean
    Stages.adaptTest
    Stages.test

    stage {
        run (fun _ -> printfn "Release")
    }

}
```

![image](https://user-images.githubusercontent.com/4760796/199828068-1558e63a-e82e-4814-897c-e423a2702541.png)

**Comment by albertwoo** [comment]
@MangelMaxime stage is just another CE. So it is very easy to reuse:

```fsharp
let checkEnv =
    stage "checkEnv" {
        run "...."
    }

pipeline "dev" {
    checkEnv
    ...
    runIfOnlySpecified 
}

pipeline "deploy" {
    checkEnv
    ...
    runIfOnlySpecified 
}
```

**Comment by albertwoo** [comment]
I also noticed that:
```fsharp
    stage "you are missing name here" {
        run (fun _ -> printfn "Release")
    }
```

**Comment by MangelMaxime** [comment]
> I also noticed that:
> 
> ```fsharp
>     stage "you are missing name here" {
>         run (fun _ -> printfn "Release")
>     }
> ```

Oops, seems like I was too tired yesterday and the error message from CE are not always that clear 😅

**Comment by albertwoo** [comment]
Yes, that is the unpleasant part of using CE. But once you are familiar with its DSL, it looks cleaner.
