### ISSUE TITLE
Ability to add condition on the pipeline?

### ISSUE THREAD

**Issue by MangelMaxime** [slaveOftime/Fun.Build#19]
Related to my workflow in #17 

I have a pipeline for the `Test` and another one for `Release`.

The `Release` pipeline, should only be able to run if `NUGET_KEY` and `GITHUB_TOKEN` variables exist. Right, now I can add the condition only on the stage. The problem, is if `NUGET_KEY` exist but `GITHUB_TOKEN` doesn't then half of the pipeline will have run.

Even worst, the pipeline will finish in a success state and it is possible for me to not see that some stages didn't complete. Would it be possible to add condition to the pipeline? And make it fail if the condition are not fulfil?

```fs
pipeline "Release" {
    description "Release the project on Nuget and GitHub"
    workingDir __SOURCE_DIRECTORY__

    Stages.clean
    Stages.adaptTest
    Stages.test

    stage "Publish packages to NuGet" {
        run "dotnet pack src -c Release"
        whenAll {
            branch "main"
            envVar "NUGET_KEY"
        }

        run (fun ctx ->
            let nugetKey = ctx.GetEnvVar "NUGET_KEY"
            cmd $"dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k {nugetKey}"
        )
    }

    stage "Release on Github" {
        whenAll {
            branch "main"
            envVar "GITHUB_TOKEN"
        }

        run (fun ctx ->
            let githubToken = ctx.GetEnvVar "GITHUB_TOKEN"
			// Do something...
		}	
}
```

**Comment by albertwoo** [comment]
@MangelMaxime from your pipeline and sematic point of view, if the GITHUB_TOKEN is not specified then "Release on Github" will not run which is expected for me. But if you want to make sure NUGET_KEY and GITHUB_TOKEN exist. You can have a env check stage like:

```fsharp
pipeline "Release" {
    stage "Check env" {
        run (fun ctx -> 
            if String.IsNullOrEmpty(ctx.GetEnvVar "NUGET_KEY") || String.IsNullOrEmpty(ctx.GetEnvVar "GITHUB_TOKEN") then
                Error "NUGET_KEY and GITHUB_TOKEN is not exist"
            else
                Ok()
        )
    }
    stage "Publish packages to NuGet" {
        ...
    }
    stage "Release on Github" {
        ...
    }	
}
```

Or we can add something like (maybe this is what you are sking for):

```fsharp
pipeline "Release" {
    // Make the pipeline fail if the condition is not met
    whenAll {
            branch "main"
            envVar "NUGET_KEY"
            envVar "GITHUB_TOKEN"
    }
    stage "Publish packages to NuGet" {
        ...
    }
    stage "Release on Github" {
        ...
    }	
}
```

**Comment by MangelMaxime** [comment]
The second example is indeed what I am asking for.

**Comment by MangelMaxime** [comment]
The thing with `verifyBeforeRun` is that this is a divergence compare to how the stage are set up.

For me it depends on if you prefer:
- To have 2 different syntax depending on the context 
- A similar syntax across stage/pipeline which could make it easier to remember for the consumer?

**Comment by albertwoo** [comment]
Implemented as below:

```fsharp
pipeline "pipeline-verify-demo" {
    description "Verify before pipeline start running"
    // Will throw exception when verification failed. The last rule will take effect. Below we set it for multiple times just for demo purpose.
    // You can define your own logic
    verify (fun ctx -> false)
    // To keep consistence, the condition is similar like when building stage
    whenCmdArg "verify"
    whenAll {
        cmdArg "v1"
        branch "verify"
    }
    runIfOnlySpecified
}
```
