### ISSUE TITLE
Alternative to string command to improve readability?

### ISSUE THREAD

**Issue by MangelMaxime** [slaveOftime/Fun.Build#21]
Hello,

when building complex/long command strings can quickly become hard to read.

In such situation, I like to use [BlackFox.CommandLine](https://github.com/vbfox/FoxSharp/tree/b1a00f7f0d26746ae63c5d7689f46c841213aead/src/BlackFox.CommandLine).

*String interpolation*

```fs
$"docker run -e \"POSTGRES_PASSWORD=XXXXXX\" -e \"POSTGRES_DB=XXXXX\" -p 33301:5432 --name {DOCKER_INSTANCE_NAME} -d {DOCKER_IMAGE_NAME}"
```

*Here is a screenshot to show how it looks with better syntax colouration*

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/4760796/215317373-1441fba1-bff5-4105-9479-a3cfab6f46fc.png">

*CommandLine*

```fs
CmdLine.empty
|> CmdLine.appendRaw "run"
|> CmdLine.appendRaw "-e \"POSTGRES_PASSWORD=XXXXX\""
|> CmdLine.appendRaw "-e \"POSTGRES_DB=XXXX\""
|> CmdLine.appendRaw "-p 33301:5432"
|> CmdLine.appendRaw $"--name %s{DOCKER_INSTANCE_NAME}"
|> CmdLine.appendRaw $"-d %s{DOCKER_IMAGE_NAME}"
|> CmdLine.toString
```

Would you be open to add support for `BlackFox.CommandLine` or something equivalent out of the box? If not I can add support for it via an additional package.

Example usage:

<img width="563" alt="image" src="https://user-images.githubusercontent.com/4760796/215317699-20278b70-5853-48f0-9d08-e2547da35d13.png">

I can contribute this feature by sending a PR.

**Comment by albertwoo** [comment]
I am not sure if it is worth to add another dependency to just remove just one line "CmdLine.toString"? And the way we build the command string is so different and opinionated.

**Comment by MangelMaxime** [comment]
Sometimes I am so focused on a specific problem that I don't see that indeed the benefit is only to remove `CmdLine.toString` 😅

I have another idea of why such DSL would be beneficial to related to `sensitive` command but I will open another issues when ready.
