### ISSUE TITLE
Proposition to make ability to "run sensitive" command easier to discover/more explicit?

### ISSUE THREAD

**Issue by MangelMaxime** [slaveOftime/Fun.Build#24]
Currently, the way to run sensitive command is mainly via `cmd` function.

https://github.com/slaveOftime/Fun.Build/blob/d4ea016ff5613c0f8a7e74612f67590f1bf8ab29/Fun.Build/BuiltinCmds.fs#L116-L117

Personally, I would have not expect `cmd` to be different from `run` CE operation. I was thinking that `cmd` was just limited to running `string` commands while `run` can run `string` command and functions.

Do you think it can make sense to create a `runSensitive` CE operation? I think it make it the effect of it more explicit. Of course, `runSensitive` would be limited to accept `string` or perhaps the `ctx -> string` overload because others overload could escape the "sensitive" security feature.

**Comment by albertwoo** [comment]
As mentioned in issue https://github.com/slaveOftime/Fun.Build/issues/23
I cannot make it work in CE without change the ecoding way.
But give another name can be done.

**Comment by albertwoo** [comment]
**runSensitive** function is added in 0.3.0

**Comment by MangelMaxime** [comment]
Could we go further and mark `cmd` as Obsolete?

My idea behind that is to make `runSensitive` the default and be able in the future to remove `cmd` as it is not as explicit about what it does.

**Comment by albertwoo** [comment]
Sure, added. Will release in the future.
