### ISSUE TITLE
Should the exception report be removed when reporting a Pipeline failed because of verification?

### ISSUE THREAD

**Issue by MangelMaxime** [slaveOftime/Fun.Build#25]
If a pipeline verification fails we get this output:

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/4760796/217493973-98b12f06-f6ff-46ae-ae86-d4d63844eb0f.png">

I really love how clean the summary is. I also feel like the nice formatted is enough and the exception report doesn't add real value here.

What do you think of removing the exception report?

**Comment by albertwoo** [comment]
I wanted to but do not know how (PR is welcomed), because the exception is printed by dotnet. The reason is I raised an exception to stop the pipeline or the command application.

**Comment by MangelMaxime** [comment]
In dotnet, we can call `Environment.Exit(exitCode)` to:

> Terminates this process and returns an exit code to the operating system.

In this case, I would call `Environment.Exit(1)`, `1` is to report an failed result.

**Comment by albertwoo** [comment]
Wow, learned something today.
Used it in runIfOnlySpecified, release in 0.3.0.
