### ISSUE TITLE
Unexisting pipeline exits silently.

### ISSUE THREAD

**Issue by nojaf** [slaveOftime/Fun.Build#38]
Hello,

When I run `dotnet fsi .\build.fsx -p Foobar` where the pipeline name does not exist in my `build.fsx` file, nothing happens.

Though this is fine, I suggest we show a message with `pipeline not found, did you mean ...`.

**Comment by albertwoo** [comment]
Yes, we can add that.

**Comment by albertwoo** [comment]
@nojaf it is released in 0.3.8

**Comment by nojaf** [comment]
Many thanks!
