### ISSUE TITLE
Strange behaviour when using an `EntryPoint`

### ISSUE THREAD

**Issue by MangelMaxime** [slaveOftime/Fun.Build#39]
*Sorry for the bad title, I don't really know how to name this problem 😅*

Running this code result in a stuck program

```fs
#r "nuget: Fun.Build, 0.4.2"

open Fun.Build
open System.IO

let deployPath = Path.GetFullPath "deploy"

module Stages =

    let clean =
        stage "Clean" {
            stage "Deploy" {
                run (fun _ ->
                    printfn "%A" deployPath
                )
            }

        }

    let installClient =
        stage "InstallClient" {
            run "npm install"
        }

// Default pipeline
pipeline "Run" {
    description "Run server and client locally in watch mode"

    Stages.clean
    Stages.installClient

    runIfOnlySpecified false
}


[<EntryPoint>]
let main args =
    tryPrintPipelineCommandHelp()
    0
```

It seems stuck when trying to execute the line `printfn "%A" deployPath`.

But replace the `[<EntryPoint>]` section from

```fs
[<EntryPoint>]
let main args =
    tryPrintPipelineCommandHelp()
    0
```

to simply

```fs
tryPrintPipelineCommandHelp()
```

is enough to get it working.

In a similar way, if I use the following code it works too:

```fs

// let deployPath = Path.GetFullPath "deploy"

module Stages =

    let clean =
        stage "Clean" {
            stage "Deploy" {
                run (fun _ ->
                    // printfn "%A" deployPath
					printfn "%A" (Path.GetFullPath "deploy")
                )
            }

        }
```

You should be able to replace the problem by creating a `build.fsx` with the content I provided. It is not required to create a full feature project to reproduce the problem.

---

To give a bit of context, I am working on proposing to use `Fun.Build` instead of FAKE in the SAFE Template.

Their requirements is that the user needs to use `dotnet run` in order to invoke the build system (similar to what they do with FAKE).

**Comment by MangelMaxime** [comment]
Also, moving the pipeline declaration inside the `main` function removes the problem too.

**Comment by albertwoo** [comment]
@MangelMaxime  I found below behavior, I think it is related how fsharp handle the EntryPoint when using async or task:

```fsharp
open System.IO

let deployPath = Path.GetFullPath "deploy"

printfn "1"

async {
     printfn "2 %s" deployPath
}
|> Async.RunSynchronously

[<EntryPoint>]
let main args =
    printfn "3"
    0
```

Above code can only print 1 and stuck.

**Comment by MangelMaxime** [comment]
Thank you @albertwoo for the simpler reproduction.

I opened an issue on https://github.com/dotnet/fsharp/issues/15627

I found 2 workarounds:

1. Remove the `EntryPoint` section completely:

```diff
- [<EntryPoint>]
- let main args =
-     printfn "3"
-     0
```

2. Move the `pipeline` instructions inside the `main` function

```diff
[<EntryPoint>]
let main args =
+    pipeline "Run" {
+     	// ...
+ 	}
    0
```
