### ISSUE TITLE
Console output format is not preserved

### ISSUE THREAD

**Issue by MangelMaxime** [slaveOftime/Fun.Build#40]
Hello,

It seems like the console output format is not preserved when running a command via Fun.Build compared to bash directly.

![CleanShot 2023-08-28 at 16 22 40](https://github.com/slaveOftime/Fun.Build/assets/4760796/b2b3f20f-70d7-4bf7-b136-6b7f23cb4dc0)

**Comment by albertwoo** [comment]
@MangelMaxime I am not sure how to preserve the format. And from my experience, some application's format is preserved and some are not, so not sure how to cover all use cases. Currently I just directly print it out.

**Comment by MangelMaxime** [comment]
I think this is because Fun.Build always redirect the output and then `Console.WriteLine` it.

From what I read online it seems like `OutputDataReceived` only gives you access to the text information.

Would you be ok if the behaviour was:

1. No instruction from the user, let `ProcessInfo` do its job and write the standard console output **(colours are supported)**
1. User used `ctx.RunCommandCaptureOutput`, set `RedirectStandardOutput <- true` and log the data in the console **(colours will/might not be supported)**
1. User used `noStdRedirectForStep` set `RedirectStandardOutput <- true` and don't log the data in the console
1. User used `ctx.RunCommandCaptureOutput` and `noStdRedirectForStep`, set `RedirectStandardOutput <- true` and don't log the data in the console

The reason why I would like to keep the colours is that when running tests or complex build system/project colours make it much easier to spot if something is wrong or not.

I am working on upgrading Fable infrastructure and without colours is it takes times to process everything that is happening during the build and where the error is if there is any.

**Comment by albertwoo** [comment]
We can do this, but we may delete one feature which is adding prefix for all the external output. But we can provide some help information for that feature to clearify that.

Please make a PR for this if you want to help out.

**Comment by albertwoo** [comment]
If we remove it, then it maybe a breaking changes. We can use it as flag, if prefix is needed we keep the old way of printing external console info, otherwise we should your new way. In the future we may mark **noPrefixForStep** as obsoleted.

**Comment by albertwoo** [comment]
Or we first mark **noPrefixForStep** as obsoledted, but ignore it when print external console info with your new way.

**Comment by albertwoo** [comment]
@MangelMaxime I tried to use StandardOut byte stream directly, but the color is still missing. Maybe the **Process** does not support redirect with format.

**Comment by MangelMaxime** [comment]
> Maybe the Process does not support redirect with format.

Yes it doesn't, from what I read online you only get the text data.

I didn't forget about this issue but was busy working on others improvement related to the help message. I will send a PR proposition for this issue in the coming days.
