### ISSUE TITLE
Is it possible to describe cmd argument outside of condition builder?

### ISSUE THREAD

**Issue by MangelMaxime** [slaveOftime/Fun.Build#41]
Imagine I want to allow the user to invoke a stage with an optional flag `--watch` which purpose would be to add a `watch` instruction to command.

I can write it using the code below:

```fs
pipeline "Test" {

    stage "Test" {
        run (fun ctx ->
            let isWatch =
                ctx.TryGetCmdArg "--watch"
                |> ValueOption.isSome

            let args =
                CmdLine.appendRaw "tests/Js/Main"
                >> CmdLine.appendIf isWatch "--watch"

            Cmd.dotnetWithArgs args
            |> CmdLine.toString
        )
    }

}
```

However, the `--watch` flag is not discoverable to user when invoking the program using `--help`.

If I want it to be discoverable I could rewrite the as follow:

```fs
pipeline "Test" {

    stage "Single" {
        whenNot {
            whenCmd {
                longName "--watch"
                shortName "-w"
                // Description can also support multiple lines
                description "re-run test on changes"
            }
        }

        run (fun ctx ->
            // ... Truncated for brevity
        )
    }

    stage "Watch" {
        whenCmd {
            longName "--watch"
            shortName "-w"
            // Description can also support multiple lines
            description "re-run test on changes"
        }

        
        run (fun ctx ->
            // ... Truncated for brevity
        )
    }

    runIfOnlySpecified

}
```

But then I have a duplicate definition and it not as obvious what the flow would be.

Do you think it would be possible to allow user to register `cmd` outside of the condition builder?

**Comment by albertwoo** [comment]
@MangelMaxime you can check this demo https://github.com/slaveOftime/Fun.Build/blob/master/demo-cmd.fsx#L15
With this, you can define shared cmd definition and use in different places, and when you use the latest version of Fun.Build, and check the --help, it will not print duplicate cmd arg info.

**Comment by MangelMaxime** [comment]
Hello @albertwoo,

My problem is not so much to share the definition of the cmd arg in different places but to display an help message that an optional flag `--watch` exist.

What I would like to write is something like

```fs

pipeline "Test" {

    stage "Test" {
        flag "--watch" "watch files and re-run on changes"
        
        run (fun ctx ->
            let isWatch =
                ctx.TryGetCmdArg "--watch"
                |> ValueOption.isSome

            let args =
                CmdLine.appendRaw "tests/Js/Main"
                >> CmdLine.appendIf isWatch "--watch"

            Cmd.dotnetWithArgs args
            |> CmdLine.toString
        )
    }

}
```

Where `flag --watch` have no impact on the conditions. It is just here so the help message display to the user that `--watch` exist.

I don't know if this should be called `options`, `arguments`, `flag`, or something else.

**Comment by albertwoo** [comment]
@MangelMaxime what about we provide another field like optional for whenCmd like:
```fsharp
            whenCmd {
                longName "--watch"
                shortName "-w"
                description "re-run test on changes"
                optional // with this, it's cmd info should always be printed out and the related stage should always be executed.
            }
```

**Comment by MangelMaxime** [comment]
@albertwoo This is a more clever solution 👍
