### ISSUE TITLE
Difference in help message generated between `whenCmd` and `whenCmdArg`

### ISSUE THREAD

**Issue by MangelMaxime** [slaveOftime/Fun.Build#43]
![CleanShot 2023-08-31 at 18 25 29](https://github.com/slaveOftime/Fun.Build/assets/4760796/180b77a2-6eec-4b23-a3af-c84c20ec4176)

VS

![CleanShot 2023-08-31 at 18 26 04](https://github.com/slaveOftime/Fun.Build/assets/4760796/03b059cb-dc57-4331-8ad4-b0db08f58862)

See how in the second case when using `whenCmdArg` the formatting result in `[    --debug]`.

Note: The problem is not related to `isOptional` implementation.

I suspect the problem is related to these lines:

https://github.com/slaveOftime/Fun.Build/blob/8b764b3e44f0cc68fb481ed9fc22edaabaffa622/Fun.Build/ConditionsBuilder.fs#L58-L71

But I don't know why it doesn't take the same path for generating the print.

I feel like the correct behaviour would be to generate `    [--build]` in both case, to align it with others long name.

**Comment by albertwoo** [comment]
The problem is that for whenCmd the **name** is for the short name, as for whenCmdArg, the first parameter is for the long name.

**Comment by MangelMaxime** [comment]
Ahhh I completely missed that as in my head by default I was thinking `name` was equivalent to `longName`.

Ok, so the code does take the same path it's just that I probably should improve the `[]` surrounding mechanism.

**Comment by albertwoo** [comment]
I fixed it and made it more explicity by append an OPTIONAL for the optional args in 0.4.3.
