### ISSUE TITLE
Should env variables be included in the generation of the help message?

### ISSUE THREAD

**Issue by MangelMaxime** [slaveOftime/Fun.Build#44]
Printing env variables info on the help message would make them easier to discover to the user.

While writing this issue I discovered that they are displayed when running in verbose mode : `dotnet fsi build.fsx -- --help --verbose`.

I think having them in the help message would be really nice. Something like:

```bash
Options(collected from pipeline and stages):

...

Env variables(collected from pipeline and stages):
```

But looking at the code, I feel like right now it not retrieving the `command` info and then printing them.

But instead execute the stage / pipelines, in a special mode which doesn't run the code and instead generate print message. Am I right?

Would you be interested in improving/enhancing the help message with the env variables info?

**Comment by albertwoo** [comment]
We difinitely could do that, all the info is collected with runing pipeline in special mode which is right as you mentioned.

Wouldn't it be too verbose if we include env vars, because the **command** info is sopposed to be used with command args right? I think user normally check what options they can provide in shell to control the pipeline when use shell and do not care about the env vars.

And user can aways use **--verbose** mode to see both cmd args and env vars.

**Comment by MangelMaxime** [comment]
> Wouldn't it be too verbose if we include env vars, because the **command** info is sopposed to be used with command args right?

Hum, I don't think it verbosity is a problem.

I suppose, my opinion here is coming from years of using `--help` and `man` to explore `cli` options and discover what is possible to do.

TBH I run `--help --verbose` for the first time yesterday when writing this issue and out of curiosity.

I think `--help --verbose` is of great value because it explains exactly how the pipeline works and is great for debugging. It is just perhaps not the first thing people will think in running, but perhaps this is just a matter of education in README.md etc.

**Comment by albertwoo** [comment]
Maybe we can just make description for the verbose option more clear.

**Comment by MangelMaxime** [comment]
I don't know I feel like the current verbose option does fill a need and does it fine. 

If I was to try explain my feeling, I would say this is a first time I see `--help --verbose` mixed together. My guess was that `--verbose` would print some debug information when running the program to help identify bugs or something.

Perhaps, if it was 2 distincts options like `--help` and `--describe` (or `--explain`) I would have been less "surprised".

What lead me to open this issue was that to me as a user it feels strange that `--help` doesn't contains all the available informations.

Sorry, if the wording is a bit off I rewrote this message 5 times at least 😅. I am just trying to explain my feeling and share my experience, to see if something can be improve:

- In the program itself 
- How information/documentation is presented
- Or if I was just confused by something and its on me to try digest it :)

**Comment by albertwoo** [comment]
I got your point. It is added in 0.4.3, please try.

**Comment by MangelMaxime** [comment]
Thank you :)

I will make sure to test it
