### ISSUE TITLE
Helps trying to get `paralle` works with a predicate

### ISSUE THREAD

**Issue by MangelMaxime** [slaveOftime/Fun.Build#51]
Hello @albertwoo,

In order to avoid having to duplicates definition of `stages` with complex `whenNot` and `whenCmd` I wanted to give a try to add a version of `paralle` which takes a predicates function. So I could make it depends on an arguments.

However, when trying the code below, I get `paralle with predicate: false` when I was expecting it to be run when using `dotnet fsi build.fsx -p test-bug --watch`. Do you have an idea why this is not working ?

```fs
open Fun.Build
open Fun.Build.Internal

[<AutoOpen>]
module Extensions  =

    type StageBuilder with

        /// Set if the steps in current stage should run in parallel, default value is true.
        [<CustomOperation("paralle")>]
        member inline _.paralle([<InlineIfLambda>] build: BuildStage, predicate: StageContext -> bool) =
            BuildStage(fun ctx ->
                printfn "paralle with predicate: %A" (predicate ctx)
                { build.Invoke ctx with IsParallel = predicate ctx }
            )

module Commands =

    let watch =
        CmdArg.Create(
            "-w",
            "--watch",
            "Watch for changes and recompile",
            isOptional = true
        )

    let isWatch (ctx : StageContext) =
        ctx.TryGetCmdArg watch
        |> Option.isSome

pipeline "test-bug" {
    stage "" {
        paralle Commands.isWatch
        run "echo 'Maxime'"
    }
    runIfOnlySpecified
}
```

**Comment by albertwoo** [comment]
To achive what you want to do, we need to change **IsParallel: bool** to **IsParallel: StageContext -> bool**, because the StageContext is record type which may not always keep update to the latest state.

**Comment by albertwoo** [comment]
It is a easy change. I committed and should be available in 0.5.2.

**Comment by albertwoo** [comment]
By the way, you do not need to implement the custom operation for paralle by yourshelf, I added that by default.

**Comment by MangelMaxime** [comment]
Awesome thank you 🙂
