### ISSUE TITLE
ctx.RunCommandCaptureOutput doesn't preserve newlines

### ISSUE THREAD

**Issue by nojaf** [slaveOftime/Fun.Build#52]
I'm using `ctx.RunCommandCaptureOutput` for the first time and I noticed the newlines are not preserved from the command line.

Looks like `Append` is used in https://github.com/slaveOftime/Fun.Build/blob/2dc44a430480f0573e5f8b3cee9bce9ca79a9dd5/Fun.Build/ProcessExtensions.fs#L65

Maybe, it should be `AppendLine`?

**Comment by albertwoo** [comment]
@nojaf I think you are right. It should be fixed in 1.0.3 now.

**Comment by nojaf** [comment]
Thx!
