### ISSUE TITLE
How to set up to run from a console application?

### ISSUE THREAD

**Issue by isaacabraham** [slaveOftime/Fun.Build#57]
I want to create a Fun.Build app that can be launched simply with `dotnet run`. I can't figure out how to create a "default" pipeline that will be run automatically. If I don't use `runIfOnlySpecified`, firstly I get a warning (about not assigning the `PipelineContext` to a symbol - fair enough) and secondly Fun.Build doesn't seem to pick up that pipeline.

**Comment by seankearon** [comment]
I had the same question.  So, to help future travellers on the Fun.Build path, the answer is to remove `runIfOnlySpecified` from the end of the pipeline and add `runImmediate`.  🚀 

``` fsharp
pipeline "Build Something" {
    description "Building Something"
    

    stage "Do something" {
        run "something"
    }
    
    // runIfOnlySpecified
    runImmediate
}
```
