### ISSUE TITLE
Should `collapseGithubActionLogs ` be included in Fun.Build ?

### ISSUE THREAD

**Issue by MangelMaxime** [slaveOftime/Fun.Build#61]
The `collapseGithubActionLogs` seems like a handy tool

https://github.com/slaveOftime/Fun.Build/blob/8343307d7ee4933b73c4c346f90d3d8c6d1131f4/build.fsx#L12-L17

Should it be included by default in Fun.Build to avoid redefining it in every project?

**Comment by albertwoo** [comment]
Yes, how about we put it into Fun.Build.Github, we can put multiple helpers here.

**Comment by albertwoo** [comment]
I added module called Github for this.
