### ISSUE TITLE
How can I run in parallel, but not in parallel? 😁

### ISSUE THREAD

**Issue by BennieCopeland** [slaveOftime/Fun.Build#62]
What I'm looking for is to have a Test stage with sub-stages for backend and frontend. I don't want them to run in parallel to preserve the log output, but I want them both to get ran, even if the first one fails. It wasn't apparent from the examples if this was possible. An alternative that would also be acceptable is if it kept the outputs until the end of the Test stage, and then prints them sequentially.

Edit: I want to add that I'll be running NPM from a different working directory.

**Comment by BennieCopeland** [comment]
After perusing the source code, I noticed that I can pass a working directory to RunCommand, so I've solved my issue with the following code:

```fsharp
stage "Run Tests" {
    timeout (60 * 10)
    
    // Runs both backend and frontend tests even if one fails
    // If either fails, the whole Run Tests stage fails
    run (fun ctx ->
        async {
            let! backendTests = ctx.RunCommand $"dotnet test --configuration Release --no-build --collect:\"XPlat Code Coverage\" --results-directory:\"{codeCoverageDirectory}\""
            let! frontendTests = ctx.RunCommand("npm run test:coverage", workingDir = $"{clientAppDirectory}")
            
            return
                [ backendTests; frontendTests ]
                |> Result.sequence // turn Result<unit, string>[] to Result<unit[], string>
                |> Result.map ignore // turn the Result<unit[], string] to Result<unit, string>
        })
}
```

I'm leaving this open for discussion on adding a feature to support this use case. I'm picturing something like the following:

```fsharp
// Backend and Frontend tests must pass for the Run Tests stage to pass, but Compile code coverage can fail
stage "Run Tests" {
    concurrencyMode (Run.Sequentially OnFailure.Stop) // default
    concurrencyMode (Run.Sequentially OnFailure.Continue) // runs all substages and only then fails
    concurrencyMode Run.InParallel // replaces paralle

    stage "Backend Tests" {
        mustSucceed // default is true so this isn't really needed
        run "..."
    }

    stage "Frontend Tests" {
        run "..."
    }

   stage "Compile code coverage" {
       mustSucceed false // this stages failure doesn't affect "Run Tests"
       run "..."
   }
}
```

**Comment by albertwoo** [comment]
@BennieCopeland good suggestion.

After some investigation, I added **continueOnStepFailure** for stage which should be able achieve what you are looking for.

You can try **1.1.0**

**Comment by BennieCopeland** [comment]
@albertwoo I looked at the test code for the feature, and it's close to what I was looking for but not exactly. Sorry that I wasn't clear enough. The following test case is the behavior I'm looking for:

```fsharp
    Assert.Throws<PipelineFailedException>(fun _ ->
        shouldNotBeCalled (fun fn ->
            pipeline "" {
                // all tests get ran, but the "Tests" stage fails preventing the follow on Publish stage
                stage "Tests" {
                    continueOnStepFailure
                    run (fun _ -> list.Add(1))
                    run (fun _ ->
                        list.Add(2)
                        Error ""
                    )
                    run (fun _ -> list.Add(3))
                }
                stage "Publish" {
                    run fn
                    run (fun _ -> list.Add(4))
                }
                runImmediate
            }
        )
    )
    |> ignore
    Assert.Equal<int>([ 1; 2; 3 ], list)
```

I want to have anything bad in the code base reported upfront to be fixed instead of having developers play "whack a mole" multiple times with a "fix, push, build failed" loop.

**Comment by albertwoo** [comment]
@BennieCopeland ok, how about this:

There will be 4 cases:

1. All steps are return ok then nothing to do. [Default]
2. One step failed, stop the rest of steps and mark the stage fail, and terminate the pipeline. [Default]
3. One step failed, but continue the rest steps and mark the stage failed. 
4. One step failed, but continue the rest steps and mark the stage success. [Now worked by continueOnStepFailure]

To make it more flexible and cover the 3rd option. I can introduce:
- continueStepOnStepFailure
- continueStageOnStepFailure (if true then will also make continueStepOnStepFailure to true)

continueOnStepFailure will be the shortcut for make both above options to true.

**Comment by albertwoo** [comment]
Create a PR for this, @BennieCopeland  please add some suggestions if you have.

**Comment by BennieCopeland** [comment]
Sorry for the late reply. I think we're close. I would keep `continueOnStepFailure` instead of renaming it, but make the stage fail instead of succeed. This setting then controls only if the stage should run the remaining steps. I would rename `continueStageOnStepFailure` to `ignoreStepFailures` to always pass the stage. This setting then controls how it will present it's step failures to it's parent stage.

Also, `continueOnStepFailure` and `paralle` should be mutually exclusive. The `continueOnStepFailure` should be a sequential run only thing. The `ignoreStepFailures` can be used for both sequential runs and parallel runs.

```fsharp
pipeline "" {
    // Backend, Frontend, Coverage reports, Some stage all get ran based on continueOnStepFailure
    // Backend and Frontend must succeed for Tests to succeed
    stage "Tests" {
        continueOnStepFailure
        stage "Backend" {
            run "..."
            run "..."
        }
        stage "Frontend" {
            run "..."
        }
        // Coverage reports stage always succeeds based on ignoreStepFailures
        stage "Coverage reports" {
           ignoreStepFailures
           run ".."
           run ".."
        }
        // Some fourth stage, all steps get ran, and always succeeds
        stage "Some stage" {
            continueOnStepFailure
            ignoreStepFailures
            run "..."
            run "..."
        }
    }
    // Publish only runs if Tests succeeded.
    stage "Publish" {
        run "..."
    }
}
```

**Comment by BennieCopeland** [comment]
Maybe rename `continueOnStepFailure` to `continuteStepsOnFailure` to make it more clear what the setting does.

**Comment by albertwoo** [comment]
@BennieCopeland  **continueStepsOnFailure** sounds good to me. Also I would like to use **continueStageOnFailure** instead of **ignoreStepFailures**. Because it sound more similar like **continueStepsOnFailure**.

I also do not want to limit it only to sequence execution, because I found some use cases to support those features for paralle.

Thanks for your suggestions, if there is no other big changes regarding to this, I will merge this PR soon.

**Comment by BennieCopeland** [comment]
Nope, no other suggestions.

**Comment by BennieCopeland** [comment]
Oh, looking at the updated PR, I think it's still missing a usecase.

1. On error, stop running steps, fail the stage - `continueStepsOnFailure false`
2. On error, continue running steps, fail the stage - `continueStepsOnFailure true`
3. On error, stop running steps, pass the stage - Nothing available
4. On error, continue running steps, pass the stage - `continueStageOnFailure true`

My suggestion above was that `continueStepsOnFailure` controls "stop running steps/continue running steps". And `continueStageOnFailure` controls "fail the stage/pass the stage". That's why I suggested the rename to `ignoreStepFailures`. The uses cases are then handled:

1. On error, stop running steps, fail the stage - `continueStepsOnFailure false; ignoreStepFailures false`
2. On error, continue running steps, fail the stage - `continueStepsOnFailure true; ignoreStepFailures false`
3. On error, stop running steps, pass the stage - `continueStepsOnFailure false; ignoreStepFailures true`
4. On error, continue running steps, pass the stage - `continueStageOnFailure true; ignoreStepFailures true`

**Comment by albertwoo** [comment]
Another commit is done, should cover all your use cases now

**Comment by albertwoo** [comment]
Code is merged and released

**Comment by BennieCopeland** [comment]
Looks great. Thank you!
