### ISSUE TITLE
How do you get the value of a command argument?

### ISSUE THREAD

**Issue by BennieCopeland** [slaveOftime/Fun.Build#63]
I want to have a "Seed database" pipeline for developer databases. Right now it's a hard coded connection string, but I would like to provide the option of passing in the connection string from the command line. I can see from the examples that I can have an environment variable with default values, but it's not clear how to do the same with command line arguments, if it's even possible.

**Comment by albertwoo** [comment]
It is similar as env, you can get those from when run (fun ctx -> ctx.GetCmdArgxxxx), for example:

```fsharp
#r "nuget:Fun.Build"

open Fun.Build

let options = {|
    dbConnection = CmdArg.Create(shortName = "-c", longName = "--connection")
|}

pipeline "demo" {
    stage "migration" {
        whenCmdArg options.dbConnection // this can provide help info for cmd help
        run (fun ctx ->
            let connection = ctx.TryGetCmdArg(options.dbConnection)
            printfn "%A" connection
        )
    }
    runIfOnlySpecified
}

tryPrintPipelineCommandHelp ()
```

**Comment by BennieCopeland** [comment]
Sorry for the late reply. That worked great, thank you!
