### ISSUE TITLE
orphaned process when using cancellation token

### ISSUE THREAD

**Issue by joprice** [slaveOftime/Fun.Build#68]
In some cases, when using a cancellation token to kill a long-running process, the underlying process is orphaned. The case I'm experiencing is when running a command like `dotnet fable watch`, where dotnet spawns it's own process. I can reproduce this orphaning by calling `kill -9` on the dotnet process, which will exit immediately without cleaning up its children. I see the same when calling `Cancel` on the token, which results in `Kill()` being called on the process, leaving only the fable process running. 

At first I thought this was a race condition, but I tried many different approaches like `WaitForExit` or checking `HasExited` to wait for the child processes to die. Only setting `UseShellExecute` to `true` made it clean up the child process, but I'm not sure of the other implications of setting that field. Perhaps it could be another optional argument exposes like `cancellationToken`?

**Comment by joprice** [comment]
In some cases, even with this flag set, I still get orphaned processes, so not sure what the right fix should be.

**Comment by joprice** [comment]
It seems that sigkill is being sent instead of term, and might need an extern definition to expose the ability to send sigterm and trigger graceful shutdown https://stackoverflow.com/questions/41041730/net-core-app-how-to-send-sigterm-to-child-processes

**Comment by joprice** [comment]
I tried with a variant of this wrapper https://github.com/rfvgyhn/min-ed-launcher/blob/master/src/MinEdLauncher/Interop.fs around the kill that allows passing sigterm and it seems to work so far.

**Comment by albertwoo** [comment]
@joprice thanks for your code snipits, I tried to merge that. Please check the PR, give me the feedback if you have any: https://github.com/slaveOftime/Fun.Build/pull/70

**Comment by joprice** [comment]
No specific feedback, but I can try with my local setup if you want before you merge. I'm reproducing this with code like the following

```fsharp
type StageBuilder with
    [<CustomOperation "runInGroup">]
    member inline this.runInGroup
      (stage, command: string, cts: CancellationTokenSource, ?workingDir)
      =
      this.run (
        stage,
        (fun (ctx: StageContext) -> async {
          try
            let! result =
              ctx.RunCommand2(command, ?workingDir = workingDir, cancellationToken = cts.Token)
            if Result.isError result then
              cts.Cancel()
            return result
          with e ->
            cts.Cancel()
            return Error e.Message
        })
      )

pipeline "watch" {
    let cts = new CancellationTokenSource()
    stage "" {
      paralle
      buildServer cts
      runServer cts
    }
    runIfOnlySpecified
}
```

where buildServer/runServer are two long-lived processes watching files and RunCommand2 is a local copy-pasta with the above fixes.

Wondering if this could be a useful custom operation, something like `failFast` or `interruptOnFailure` when running a group of parallel commands.

**Comment by albertwoo** [comment]
@joprice do you mean the canncellation is still not working for your case? (orpahaned process).

I added a new test like this: https://github.com/slaveOftime/Fun.Build/pull/70/commits/7de7a0b3a49dc04559dd17f4cb27df3cad533e23#diff-06f56a43f72243b0af06d49ee6df95df4899e5ff12895eb965dc29aec8c8f831
And it seems working as expected on linux.

**Comment by joprice** [comment]
I haven't had time to test. I imagine it will as the changes you made are pretty much the same as I had.

**Comment by albertwoo** [comment]
Please try.

Regarding to failfast, by default it should work for parallel steps. But I found there is  a bug for command step, so I also improved that.

**Comment by joprice** [comment]
I tried it out and it's working as expected. I was able to remove my runInGroup helper and just use simple `run`'s  and things fail fast as expected. Thanks for the quick response and fix!

**Comment by albertwoo** [comment]
Code merged. Thanks for your contribution.
