### ISSUE TITLE
add sensitive flag to RunCommandCaptureOutput

### ISSUE THREAD

**Issue by joprice** [slaveOftime/Fun.Build#71]
I'm running a command that unfortunately requires the password to be passed explicitly, where I also want to capture the output, however currently the features of `RunCommandCaptureOutput` and `RunSensitive` are exclusive of each other. Would it make sense to either merge them or add a sensitive flag to the capture output version?

**Comment by albertwoo** [comment]
I will do that in the future weeks. Recently I am quite busy.
