### ISSUE TITLE
idea: use "concurrent" instead of "paralle"

### ISSUE THREAD

**Issue by joprice** [slaveOftime/Fun.Build#72]
Since `parallel` is a reserved keyword, forcing the awkward `paralle` to be used, and technically "concurrent" is a more accurate description of how the processes are executed, I'd suggest this alternative that I've been using locally:

```fsharp
[<CustomOperation("concurrent")>]
member inline _.concurrent([<InlineIfLambda>] build: BuildStage) =
    BuildStage(fun ctx -> { build.Invoke ctx with IsParallel = fun _ -> true })

Is there any reason to not offer this as an alternative?

**Comment by albertwoo** [comment]
Yes, we can provide that.
