### ISSUE TITLE
Allow other exit codes

### ISSUE THREAD

**Issue by nojaf** [slaveOftime/Fun.Build#8]
Hello,

I currently am running an `F#` script in a stage block and for some reason, my script exits with code `139`.
The script ran to completion and did do what it is supposed to do.
It occurs on Linux and not on Windows and it is currently quite a mystery what is happening.

```fsharp
stage "lint" {
    run "dotnet fsi my-script.fsx"
}
```

Long story short, I was wondering if we could add something that allows some other exit code to be considered "ok" as well.

Something like

```fsharp
stage "lint" {
    run "dotnet fsi my-script.fsx"
    accept_exit_codes [| 0; 139 |]
}
```

Where the default is `[| 0 |]`, but you can supply other codes as well.
If my script were to fail and it returns `1`, the stage should still fail.

Does this seem reasonable and would you accept a contribution?

**Comment by albertwoo** [comment]
@nojaf  For me it is ok, because I think exit code is just a convention. So it should be allowed to override it.

And it should be allowed to set under pipeline too.

Contribution is always welcomed. Just make a PR. If you do not have time I can also implement that too.
