### ISSUE TITLE
Can we add support for `remaining` arguments?

### ISSUE THREAD

**Issue by MangelMaxime** [slaveOftime/Fun.Build#81]
In CLI application, it is often that you can use `--` to say anything after this instruction should be ignored. For example, Fable use it to forward CLI arguments to subprocess or `dotnet fsi` make it possible to forward `--help` instruction to Fun.Build (`dotnet fsui build.fsx -- --help`).

Fun.Build doesn't seems to understand `--` for example, if I write `dotnet fsi build.fsx -- -p release -- --help` then it will display the help message instead of executing the `release` pipeline.

Would you be ok with providing `--` support for Fun.Build? If yes, we could add a `ctx.RemainingArgs` or `ctx.RemainingArgs ()` to access it easily. 

My use case for it, is that I am heavily relying on CLI tools and sometimes I want to be able to forward arguments from Fun.Build invocation to the CLI tools.

Regarding the name I used `remaining` because Spectre.Console.CLI is using that term.

**Comment by albertwoo** [comment]
I am good with that, PR is welcomed.

**Comment by albertwoo** [comment]
1.1.15 is released with this, please try.
